[[redirects]]
  from = "/*"
  to = "/vision.html"
  status = 200

  [[plugins]]
  package = "@netlify/plugin-nextjs"


  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME"